<Project Sdk="Godot.NET.Sdk/4.7.2">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <AssemblyName>Gameplay</AssemblyName>
    <RootNamespace></RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Animations\Animations.csproj" />
    <ProjectReference Include="..\Core\Core.csproj" />
  </ItemGroup>
</Project>